[package]
name = "receipt-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tesseract = "0.15.2"
fuzzy-matcher = "0.3"
walkdir = "2.0"
regex = "1.0"
prettytable-rs = "0.10"
anyhow = "1.0"
